# Docker Compose build file: docker-compose -f build.yml build
version: "3.7"

services:
  pihole-local:
    build:
      context: .
      args:
        PIHOLE_BASE: debian:${DEBIAN_VERSION:-buster}-slim
        PIHOLE_VERSION: ${PIHOLE_VERSION}
        NAME: pihole/pihole
        S6_VERSION: v2.1.0.2
        PHP_ENV_CONFIG: /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
        PHP_ERROR_LOG: /var/log/lighttpd/error.log
